-- REMEMBER: auto_increment(like mysql) => id bigint generated by default as identity (start with 1)
-- CREATE TABLE users (
-- 	id bigint generated by default as identity (start with 1),
-- 	real_name varchar(4) NOT NULL,
-- 	nick varchar(7) NOT NULL,
-- 	account varchar(18) NOT NULL,
-- 	password varchar(32) NOT NULL,
-- 	contact varchar(11) NOT NULL,
-- 	register_time timestamp,
-- 	last_login_time timestamp,
-- 	login_times integer DEFAULT 0,
-- 	-- credit bigint DEFAULT 0,
-- 	blocked boolean DEFAULT FALSE,
-- 	CONSTRAINT user_pk PRIMARY KEY (id)
-- );

-- CREATE TABLE categories (
-- 	id bigint generated by default as identity (start with 1),
-- 	name varchar(18) NOT NULL,
-- 	description varchar(255) NOT NULL,
-- 	added_time timestamp,
-- 	extra varchar(255),
-- 	CONSTRAINT categories_pk PRIMARY KEY (id)
-- );

-- CREATE TABLE items (
-- 	id bigint generated by default as identity (start with 1),
-- 	category_id bigint NOT NULL,
-- 	name varchar(18) NOT NULL,
-- 	price float NOT NULL,
-- 	added_time timestamp,
-- 	last_modified_time timestamp,
-- 	click_times bigint DEFAULT 0,
-- 	seller_id bigint NOT NULL,
-- 	closed boolean DEFAULT FALSE,
-- 	description varchar(255) NOT NULL,
-- 	blocked boolean DEFAULT FALSE,
-- 	deal boolean DEFAULT FALSE,
-- 	extra varchar(255),
-- 	CONSTRAINT items_pk PRIMARY KEY (id),
-- 	CONSTRAINT items_category_fk FOREIGN KEY (category_id) references categories (id),
-- 	CONSTRAINT items_seller_fk FOREIGN KEY (seller_id) references users (id)
-- );

-- CREATE TABLE records (
-- 	id bigint generated by default as identity (start with 1),
-- 	occur_time timestamp NOT NULL,
-- 	item_id bigint NOT NULL,
-- 	-- buyer_id bigint,
-- 	extra varchar(255),
-- 	CONSTRAINT records_pk PRIMARY KEY (id),
-- 	-- CONSTRAINT records_buyer_fk FOREIGN KEY (buyer_id) references users (id),
-- 	CONSTRAINT records_item_fk FOREIGN KEY (item_id) references items (id)
-- );

-- CREATE TABLE admins (
-- 	id bigint generated by default as identity (start with 1),
-- 	name varchar(7) NOT NULL,
-- 	account varchar(18) NOT NULL,
-- 	password varchar(32) NOT NULL,
-- 	added_time timestamp,
-- 	last_login_time timestamp,
-- 	last_login_ip varchar(255),
-- 	extra varchar(255), 
-- 	CONSTRAINT admins_pk PRIMARY KEY (id)
-- );

INSERT INTO users (real_name, nick, account, password, contact) values ('龙凯', '爱因斯坦的狗', 'longkai', 'e10adc3949ba59abbe56e057f20f883e', '14795633343');
INSERT INTO users (real_name, nick, account, password, contact) values ('你好', '斯诺登', 'hello', 'e10adc3949ba59abbe56e057f20f883e', '14795633343');
INSERT INTO users (real_name, nick, account, password, contact) values ('世界', '我叫拜登', 'world', 'e10adc3949ba59abbe56e057f20f883e', '14795633343');
INSERT INTO users (real_name, nick, account, password, contact) values ('测试', '我叫Obama', 'test123', 'e10adc3949ba59abbe56e057f20f883e', '14795633343');

INSERT INTO categories (name, description) values ('日用百货', '各种日用百货。。。');
INSERT INTO categories (name, description) values ('新旧书市', '各种新旧书市。。。');
INSERT INTO categories (name, description) values ('家用电器', '各种家用电器。。。');
INSERT INTO categories (name, description) values ('电子产品', '各种电子产品。。。');

INSERT INTO items (category_id, name, price, seller_id, description) values
	(1, '梳妆镜', 69, 1, '创意礼品生日礼物送女友送妈妈男女老少人手一个，送礼自用都可以的！');
INSERT INTO items (category_id, name, price, seller_id, description) values
	(2, '易中天中华史：祖先', 18.9, 1, '看清自己，必定先要追根寻源。神话和传说，都是民族的童年记忆，无不隐含着某种文化的秘密和梦想。神的历史就是人的历史，是人类自我认识的心灵史。只要抹去神秘的色彩，我们就能打开迷宫，依稀看见一些真实的东西。
　　《易中天中华史：祖先》和您一起探寻中华文明的源头，发现我们祖先——女娲、夏娃、伏羲、炎黄、尧舜的本来面目。');
INSERT INTO items (category_id, name, price, seller_id, description) values
	(2, '大数据：正在到来的数据革命', 37.4, 2, '入榜《亚洲周刊》“年度十大好书”，持续畅销；叫醒中国，领跑大数据时代最好的书.');
INSERT INTO items (category_id, name, price, seller_id, description) values
	(3, '格力台式转页扇', 88, 4, '精致美观，120分钟定时，优质电机，真正好品质！');
INSERT INTO items (category_id, name, price, seller_id, description) values
	(3, '飞利浦均衡呵护系列电吹风', 139, 3, '离子设计 1600瓦仅需139，55度恒温技术，负离子护发，深层养护，用心呵护您秀发的健康！');
INSERT INTO items (category_id, name, price, seller_id, description) values
	(4, '九阳全自动面条机', 699, 2, '行业专家 1000次揉和 DIY多彩多样筋道营养面！');
INSERT INTO items (category_id, name, price, seller_id, description) values
	(2, '高清LED液晶电视', 88, 4, '精致美观，120分钟定时，优质电机，真正好品质！');

INSERT INTO admins (name, account, password) values ('超级管理员', 'admin123', 'e10adc3949ba59abbe56e057f20f883e');