-- REMEMBER: auto_increment(like mysql) => id bigint generated by default as identity (start with 1)
CREATE TABLE users (
	id bigint generated by default as identity (start with 1),
	real_name varchar(4) NOT NULL,
	nick varchar(7) NOT NULL,
	account varchar(18) NOT NULL,
	password varchar(32) NOT NULL,
	contact varchar(11) NOT NULL,
	register_time timestamp,
	last_login_time timestamp,
	login_times integer DEFAULT 0,
	-- credit bigint DEFAULT 0,
	blocked boolean DEFAULT FALSE,
	CONSTRAINT user_pk PRIMARY KEY (id)
);

CREATE TABLE categories (
	id bigint generated by default as identity (start with 1),
	name varchar(18) NOT NULL,
	description varchar(255) NOT NULL,
	added_time timestamp,
	extra varchar(255),
	CONSTRAINT categories_pk PRIMARY KEY (id)
);

CREATE TABLE items (
	id bigint generated by default as identity (start with 1),
	category_id bigint NOT NULL,
	name varchar(18) NOT NULL,
	price float NOT NULL,
	added_time timestamp,
	last_modified_time timestamp,
	click_times bigint DEFAULT 0,
	seller_id bigint NOT NULL,
	closed boolean DEFAULT FALSE,
	description varchar(255) NOT NULL,
	blocked boolean DEFAULT FALSE,
	deal boolean DEFAULT FALSE,
	extra varchar(255),
	CONSTRAINT items_pk PRIMARY KEY (id),
	CONSTRAINT items_category_fk FOREIGN KEY (category_id) references categories (id),
	CONSTRAINT items_seller_fk FOREIGN KEY (seller_id) references users (id)
);

CREATE TABLE records (
	id bigint generated by default as identity (start with 1),
	occur_time timestamp NOT NULL,
	item_id bigint NOT NULL,
	-- buyer_id bigint,
	extra varchar(255),
	CONSTRAINT records_pk PRIMARY KEY (id),
	-- CONSTRAINT records_buyer_fk FOREIGN KEY (buyer_id) references users (id),
	CONSTRAINT records_item_fk FOREIGN KEY (item_id) references items (id)
);

CREATE TABLE admins (
	id bigint generated by default as identity (start with 1),
	name varchar(7) NOT NULL,
	account varchar(18) NOT NULL,
	password varchar(32) NOT NULL,
	added_time timestamp,
	last_login_time timestamp,
	last_login_ip varchar(255),
	extra varchar(255),
	CONSTRAINT admins_pk PRIMARY KEY (id)
);
